"use client";
import React, { useState } from 'react';
import {  motion } from 'framer-motion';
import { staggerContainer, fadeUpBounce } from '../../utils/animations';
import { useTheme } from '../../context/ThemeContext';
import {
  Users, Lock, ShieldAlert, Activity, ClipboardList,
  ChevronRight, CheckCircle2, XCircle, AlertTriangle, Clock
, ArrowRight } from 'lucide-react';

const sections = [
  {
    id: 'sub_admins',
    title: 'Sub Admins',
    description: 'Manage branch-level admin accounts and their access privileges across all locations.',
    icon: Users,
    accentColor: '#4f46e5',
    stats: [{ label: 'Total', value: 8 }, { label: 'Active', value: 7 }, { label: 'Branches', value: 6 }],
    items: [
      { name: 'Arjun Pillai', detail: 'Chennai HQ – Full Access', status: 'active' },
      { name: 'Ritu Joshi', detail: 'Mumbai Branch – Visitor Only', status: 'active' },
      { name: 'Deepa Nair', detail: 'Hyderabad – Visitor + Reports', status: 'active' },
      { name: 'Vikram Singh', detail: 'Delhi NCR – Full Access', status: 'inactive' },
      { name: 'Anita Desai', detail: 'Pune – Visitor Only', status: 'active' },
    ],
  },
  {
    id: 'roles_permissions',
    title: 'Roles & Permissions',
    description: 'Define role-based access rules controlling what each user type can see and do.',
    icon: Lock,
    accentColor: '#7c3aed',
    stats: [{ label: 'Roles', value: 6 }, { label: 'Permissions', value: 24 }, { label: 'Policies', value: 12 }],
    items: [
      { name: 'Super Admin', detail: 'Full system access', status: 'active' },
      { name: 'Org Admin', detail: 'Branch-level full access', status: 'active' },
      { name: 'HR', detail: 'Employee + Visitor management', status: 'active' },
      { name: 'Security', detail: 'Check-in/out + Verification', status: 'active' },
      { name: 'Receptionist', detail: 'Visitor passes + Bookings', status: 'active' },
    ],
  },
  {
    id: 'access_control',
    title: 'Access Control',
    description: 'Configure physical and digital security zones with granular entry restrictions.',
    icon: ShieldAlert,
    accentColor: '#dc2626',
    stats: [{ label: 'Zones', value: 5 }, { label: 'Secured Areas', value: 12 }, { label: 'IP Rules', value: 3 }],
    items: [
      { name: 'Zone A – Executive Floor', detail: 'RFID + Biometric', status: 'active' },
      { name: 'Zone B – Server Room', detail: 'Biometric Only', status: 'active' },
      { name: 'Zone C – HR Office', detail: 'Badge Access', status: 'active' },
      { name: 'Zone D – Meeting Rooms', detail: 'Visitor Pass', status: 'active' },
      { name: 'Zone E – Public Lobby', detail: 'Open Access', status: 'inactive' },
    ],
  },
  {
    id: 'login_activity',
    title: 'Login Activity',
    description: 'Monitor all login sessions, detect anomalies, and audit authentication events.',
    icon: Activity,
    accentColor: '#0284c7',
    stats: [{ label: 'Sessions Today', value: 42 }, { label: 'Failed', value: 3 }, { label: 'Active Now', value: 8 }],
    items: [
      { name: 'admin@forgeindia.com', detail: 'Chrome · Chennai · 09:12 AM', status: 'active' },
      { name: 'arjun.pillai@forgeindia.com', detail: 'Edge · Mumbai · 09:45 AM', status: 'active' },
      { name: 'ritu.joshi@forgeindia.com', detail: 'Firefox · Hyderabad · 10:01 AM', status: 'active' },
      { name: 'unknown@example.com', detail: 'Safari · Unknown IP · 10:22 AM', status: 'failed' },
      { name: 'deepa.nair@forgeindia.com', detail: 'Chrome · Pune · 11:05 AM', status: 'active' },
    ],
  },
  {
    id: 'audit_logs',
    title: 'Audit Logs',
    description: 'Full chronological record of all data changes, access events, and system actions.',
    icon: ClipboardList,
    accentColor: '#b45309',
    stats: [{ label: 'Logs Today', value: 234 }, { label: 'Critical', value: 2 }, { label: 'Data Changes', value: 18 }],
    items: [
      { name: '[10:22] WARN', detail: 'Failed login – unknown@example.com', status: 'failed' },
      { name: '[10:18] INFO', detail: 'Pass VB-005 generated by admin', status: 'active' },
      { name: '[10:05] INFO', detail: 'Employee EMP-048 profile updated', status: 'active' },
      { name: '[09:55] CRIT', detail: 'Zone B access denied – VB-003', status: 'failed' },
      { name: '[09:40] INFO', detail: 'Chennai: visitor capacity updated', status: 'active' },
    ],
  },
];

export default function AdministrationOverview({ setActiveTab }) {
  const { isDark } = useTheme();
  
  const glass = {
    background: isDark ? 'rgba(30,41,59,0.7)' : '#ffffff',
    backdropFilter: 'blur(20px)',
    border: isDark ? '1px solid rgba(255,255,255,0.07)' : '1px solid rgba(0,0,0,0.05)',
    borderRadius: 20,
    boxShadow: isDark ? '0 4px 24px rgba(0,0,0,0.25)' : '0 4px 24px rgba(148,163,184,0.1)',
  };

  return (
    <motion.div variants={staggerContainer} initial="hidden" animate="visible"
      style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>

      {/* Page Header */}
      <motion.div variants={fadeUpBounce}>
        <h2 style={{ margin: 0, fontSize: 26, fontWeight: 800, color: isDark ? '#f8fafc' : '#0f172a' }}>
          Administration
        </h2>
        <p style={{ margin: '6px 0 0', fontSize: 14, color: isDark ? '#94a3b8' : '#64748b' }}>
          Manage sub-admins, roles, access zones, login sessions, and audit trails — all in one place.
        </p>
      </motion.div>

      {/* Section Cards Grid */}
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 24 }}>
        {sections.map((section) => {
          const Icon = section.icon;

          return (
            <motion.div
              key={section.id}
              variants={fadeUpBounce}
              whileHover={{ y: -6, transition: { duration: 0.2 } }}
              onClick={() => setActiveTab && setActiveTab(section.id)}
              style={{
                ...glass,
                display: 'flex',
                flexDirection: 'column',
                cursor: 'pointer',
                overflow: 'hidden',
                position: 'relative'
              }}
            >
              {/* Top Accent Line */}
              <div style={{ height: 4, width: '100%', background: section.accentColor }} />
              
              <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', flex: 1 }}>
                
                {/* Header: Icon + Title */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 16 }}>
                  <div style={{
                    width: 52, height: 52, borderRadius: 14, flexShrink: 0,
                    background: isDark ? (section.accentColor + '20') : (section.accentColor + '15'),
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: section.accentColor,
                  }}>
                    <Icon size={26} strokeWidth={2.5} />
                  </div>
                  <h3 style={{ margin: 0, fontSize: 18, fontWeight: 800, color: isDark ? '#f8fafc' : '#0f172a' }}>
                    {section.title}
                  </h3>
                </div>

                {/* Description */}
                <p style={{ 
                  margin: 0, fontSize: 14, color: isDark ? '#94a3b8' : '#64748b', 
                  lineHeight: 1.5, flexGrow: 1 
                }}>
                  {section.description}
                </p>

                {/* Bottom Stats & Arrow */}
                <div style={{ 
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center', 
                  marginTop: 24, paddingTop: 16, 
                  borderTop: isDark ? '1px solid rgba(255,255,255,0.06)' : '1px solid rgba(0,0,0,0.06)' 
                }}>
                  <div style={{ display: 'flex', gap: 12 }}>
                    {section.stats.map(s => (
                      <div key={s.label}>
                        <p style={{ margin: 0, fontSize: 15, fontWeight: 800, color: isDark ? '#e2e8f0' : '#334155' }}>
                          {s.value}
                        </p>
                        <p style={{ margin: 0, fontSize: 11, color: isDark ? '#64748b' : '#94a3b8', fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                          {s.label}
                        </p>
                      </div>
                    ))}
                  </div>
                  
                  <div style={{ 
                    width: 32, height: 32, borderRadius: '50%', 
                    background: isDark ? 'rgba(255,255,255,0.05)' : '#f1f5f9',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: section.accentColor
                  }}>
                    <ArrowRight size={16} strokeWidth={3} />
                  </div>
                </div>

              </div>
            </motion.div>
          );
        })}
      </div>
    </motion.div>
  );
}
