"use client";
/**
 * GenericModule.jsx
 * Sub-module detail view for Reports, Administration, Notifications, Verification, Settings.
 */
import React from 'react';
import { motion } from 'framer-motion';
import { staggerContainer, fadeUpBounce } from '../../utils/animations';
import { useTheme } from '../../context/ThemeContext';
import { ArrowLeft, Download, Printer } from 'lucide-react';

const moduleContent = {
  // ─── Administration ───
  sub_admins: {
    title: 'Sub Admins', icon: '🛡️', category: 'administration',
    stats: [{ label: 'Total Sub-Admins', value: 8 }, { label: 'Active', value: 7 }, { label: 'Branches Covered', value: 6 }],
    items: ['Arjun Pillai – Chennai HQ – Full Access', 'Ritu Joshi – Mumbai Branch – Visitor Only', 'Deepa Nair – Hyderabad – Visitor + Reports', 'Vikram Singh – Delhi NCR – Full Access', 'Anita Desai – Pune – Visitor Only'],
    accentColor: '#4f46e5',
  },
  roles_permissions: {
    title: 'Roles & Permissions', icon: '🔐', category: 'administration',
    stats: [{ label: 'Roles Defined', value: 6 }, { label: 'Custom Permissions', value: 24 }, { label: 'Policy Rules', value: 12 }],
    items: ['Super Admin – Full system access', 'Org Admin – Branch-level full access', 'HR – Employee + visitor management', 'Security – Check-in/out + verification', 'Receptionist – Visitor passes + bookings', 'Employee – View-only personal data'],
    accentColor: '#7c3aed',
  },
  access_control: {
    title: 'Access Control', icon: '🔒', category: 'administration',
    stats: [{ label: 'Secured Areas', value: 12 }, { label: 'Zones', value: 5 }, { label: 'IP Restrictions', value: 3 }],
    items: ['Zone A: Executive Floor – RFID + Biometric', 'Zone B: Server Room – Biometric Only', 'Zone C: HR Office – Badge Access', 'Zone D: Meeting Rooms – Visitor Pass', 'Zone E: Public Lobby – Open Access'],
    accentColor: '#dc2626',
  },
  login_activity: {
    title: 'Login Activity', icon: '📡', category: 'administration',
    stats: [{ label: 'Sessions Today', value: 42 }, { label: 'Failed Logins', value: 3 }, { label: 'Active Sessions', value: 8 }],
    items: ['admin@forgeindia.com – Chrome – Chennai – 09:12 AM ✓', 'arjun.pillai@forgeindia.com – Edge – Mumbai – 09:45 AM ✓', 'ritu.joshi@forgeindia.com – Firefox – Hyderabad – 10:01 AM ✓', 'unknown@example.com – Safari – Unknown IP – 10:22 AM ✗ FAILED', 'deepa.nair@forgeindia.com – Chrome – Pune – 11:05 AM ✓'],
    accentColor: '#0284c7',
  },
  audit_logs: {
    title: 'Audit Logs', icon: '📋', category: 'administration',
    stats: [{ label: 'Logs Today', value: 234 }, { label: 'Critical Events', value: 2 }, { label: 'Data Changes', value: 18 }],
    items: ['[10:22] WARN  – Failed login attempt – unknown@example.com', '[10:18] INFO  – Visitor VB-005 pass generated by admin', '[10:05] INFO  – Employee EMP-048 profile updated', '[09:55] CRIT  – Access denied: Zone B attempted by VB-003', '[09:40] INFO  – Branch Chennai: visitor capacity updated to 150'],
    accentColor: '#b45309',
  },

  // ─── Reports & Analytics ───
  daily_reports: {
    title: 'Daily Reports', icon: '📊', category: 'reports_analytics',
    stats: [{ label: 'Reports Generated', value: 6 }, { label: 'Total Visitors', value: 255 }, { label: 'Avg Check-in Time', value: '4.2 min' }],
    items: ['All Branches Daily Summary – Today', 'Visitor Type Breakdown – Guest: 112, Vendor: 87, VIP: 34, Interviewee: 22', 'Peak Hour Report – 10:00–11:30 AM (68 visitors)', 'Security Incidents – 1 flagged (High Risk visitor)', 'Approval Rate – 94.2% approved, 5.8% rejected'],
    accentColor: '#4f46e5',
  },
  weekly_reports: {
    title: 'Weekly Reports', icon: '📅', category: 'reports_analytics',
    stats: [{ label: 'Week Total', value: 1240 }, { label: 'Growth vs Last Week', value: '+8.4%' }, { label: 'Branches Reported', value: 6 }],
    items: ['Weekly Summary: 1,240 visitors across 6 branches', 'Top Branch: Chennai HQ – 412 visitors', 'Highest Growth: Mumbai +14.2% week-on-week', 'Most Common Purpose: Business Meeting (38%)', 'Average Dwell Time: 2.3 Hours'],
    accentColor: '#7c3aed',
  },
  monthly_reports: {
    title: 'Monthly Reports', icon: '🗓️', category: 'reports_analytics',
    stats: [{ label: 'Month Total', value: 4820 }, { label: 'New Branches', value: 1 }, { label: 'Compliance Rate', value: '96.8%' }],
    items: ['Monthly Overview – 4,820 total visitors, ↑12% growth', 'Branch Expansion: Tech Park location active', 'Compliance Score: 96.8% average across all branches', 'Top Visitor Category: Vendor (42% of all visits)', 'Zero data breach incidents – 100% ID verification rate'],
    accentColor: '#0891b2',
  },
  visitor_trends: {
    title: 'Visitor Trends', icon: '📈', category: 'reports_analytics',
    stats: [{ label: 'YTD Visitors', value: '28.4K' }, { label: 'MoM Growth', value: '+12%' }, { label: 'Peak Period', value: 'Q2 2026' }],
    items: ['Q1 2026: 9,240 visitors – Baseline period', 'Q2 2026: 11,400 visitors – +23.4% growth', 'Fastest growing category: VIP visits (+34% YoY)', 'Seasonal peak: Q2 travel surge', 'Predicted all-time high: Q3 (2,400+ expected)'],
    accentColor: '#10b981',
  },
  peak_visit_hours: {
    title: 'Peak Visit Hours', icon: '⏰', category: 'reports_analytics',
    stats: [{ label: 'Busiest Hour', value: '10 AM' }, { label: 'Avg Daily Peak', value: '9–11 AM' }, { label: 'Slowest Period', value: '2–3 PM' }],
    items: ['Morning Rush (9–11 AM): 42% of daily visits', 'Post-Lunch Lull (1–3 PM): 12% of daily visits', 'Evening Surge (4–6 PM): 28% of daily visits', 'Friday is busiest day (18% above weekly avg)', 'Monday mornings show highest no-show rate (11%)'],
    accentColor: '#f59e0b',
  },
  export_reports: {
    title: 'Export Reports', icon: '⬇️', category: 'reports_analytics',
    stats: [{ label: 'Formats Available', value: 4 }, { label: 'Last Export', value: 'Today' }, { label: 'Scheduled Exports', value: 3 }],
    items: ['📄 PDF – Full formatted report with charts', '📊 Excel (.xlsx) – Raw data for analysis', '📋 CSV – Universal data format', '📧 Email Delivery – Schedule weekly/monthly auto-sends', '🔗 API Export – Integrate with your BI tool'],
    accentColor: '#06b6d4',
  },

  // ─── Employee Sub-tabs ───
  department_management: {
    title: 'Department Management', icon: '🏛️', category: 'employee_management',
    stats: [{ label: 'Departments', value: 12 }, { label: 'Employees', value: 821 }, { label: 'Open Roles', value: 7 }],
    items: ['Engineering – 245 employees – Dept Head: Nikhil Sharma', 'Sales & Marketing – 134 employees – Dept Head: Raj Kumar', 'HR & Administration – 89 employees – Dept Head: Sunita Rao', 'Finance & Accounts – 76 employees – Dept Head: Anika Bose', 'Operations – 112 employees – Dept Head: Deepa Nair'],
    accentColor: '#4f46e5',
  },
  host_directory: {
    title: 'Host Directory', icon: '👤', category: 'employee_management',
    stats: [{ label: 'Total Hosts', value: 312 }, { label: 'Available Now', value: 187 }, { label: 'In Meeting', value: 64 }],
    items: ['Priya Nair – Engineering – priya.nair@forgeindia.com – ✓ Available', 'Raj Kumar – Sales – raj.kumar@forgeindia.com – ✓ Available', 'Anika Bose – Finance – anika.bose@forgeindia.com – 🔴 In Meeting', 'Dev Singh – IT – dev.singh@forgeindia.com – ✓ Available', 'Geeta Singh – Legal – geeta.singh@forgeindia.com – 🟡 Away'],
    accentColor: '#7c3aed',
  },

  // ─── Notifications ───
  sms_notifications: {
    title: 'SMS Notifications', icon: '📱', category: 'notifications',
    stats: [{ label: 'Sent Today', value: 342 }, { label: 'Delivery Rate', value: '98.7%' }, { label: 'Templates', value: 8 }],
    items: ['Visitor Arrival Alert – "Your visitor [Name] has arrived at Reception"', 'Pass Generated – "[Name], your pass [ID] is ready. Show QR at gate."', 'Meeting Reminder – "Your meeting with [Host] starts in 15 minutes"', 'Check-out Confirmation – "Visit complete. Thank you for visiting Forge India."', 'Security Alert – "⚠ Flagged visitor attempting entry at [Branch]"'],
    accentColor: '#10b981',
  },
  email_notifications: {
    title: 'Email Notifications', icon: '📧', category: 'notifications',
    stats: [{ label: 'Sent Today', value: 218 }, { label: 'Open Rate', value: '74.3%' }, { label: 'Templates', value: 12 }],
    items: ['Welcome Email – Sent to visitor upon pass generation', 'Host Alert – Notifies host when visitor checks in', 'Approval Request – Sent to host for meeting approval', 'Daily Digest – Admin summary of all visits (7 AM daily)', 'Expiry Warning – Notifies visitor 30 min before pass expires'],
    accentColor: '#4f46e5',
  },
  push_notifications: {
    title: 'Push Notifications', icon: '🔔', category: 'notifications',
    stats: [{ label: 'Active Devices', value: 84 }, { label: 'Sent Today', value: 156 }, { label: 'Click Rate', value: '62.1%' }],
    items: ['Real-time visitor arrival alerts to mobile app', 'Security incident push to all Security role users', 'Approval requests to host devices instantly', 'Check-in/out updates to reception staff', 'Branch manager daily KPI summary at 6 PM'],
    accentColor: '#7c3aed',
  },
  alert_center: {
    title: 'Alert Center', icon: '🚨', category: 'notifications',
    stats: [{ label: 'Active Alerts', value: 4 }, { label: 'Critical', value: 1 }, { label: 'Resolved Today', value: 12 }],
    items: ['🔴 CRITICAL: High-risk visitor AQ-004 awaiting clearance – Zone B attempted', '🟡 WARN: Main branch under maintenance – visitor capacity updated', '🟡 WARN: Renewal check scheduled', '🔵 INFO: Scheduled server maintenance at 2:00 AM', '✅ RESOLVED: Login anomaly flagged – Blocked & logged'],
    accentColor: '#ef4444',
  },

  // ─── Verification Center ───
  qr_pass_generator: {
    title: 'QR Pass Generator', icon: '🔲', category: 'verification_center',
    stats: [{ label: 'Generated Today', value: 87 }, { label: 'Active Passes', value: 54 }, { label: 'Scanned', value: 73 }],
    items: ['Auto-generate QR passes on visitor approval', 'Time-limited QR codes (expire at check-out)', 'Supports visitor self-service QR via SMS/Email', 'Multi-pass batch generation for large groups', 'Integration with physical access control systems'],
    accentColor: '#0284c7',
  },
  qr_scan_logs: {
    title: 'QR Scan Logs', icon: '📷', category: 'verification_center',
    stats: [{ label: 'Scans Today', value: 214 }, { label: 'Successful', value: 208 }, { label: 'Failed/Invalid', value: 6 }],
    items: ['[10:45 AM] PASS V-2041 – Kartik Mehta – Gate A – ✓ Valid', '[10:42 AM] PASS V-2040 – Preethi Suresh – Gate B – ✓ Valid', '[10:38 AM] PASS V-1998 – Ravi Verma – Gate A – ✗ Expired', '[10:30 AM] PASS V-2039 – Akash Singh – Gate C – ✓ Valid', '[10:22 AM] UNKNOWN QR – Unregistered code – Gate B – ✗ BLOCKED'],
    accentColor: '#10b981',
  },
  visitor_verification: {
    title: 'Visitor Verification', icon: '✅', category: 'verification_center',
    stats: [{ label: 'Verified Today', value: 87 }, { label: 'Pending ID Check', value: 6 }, { label: 'Failed Verification', value: 2 }],
    items: ['Aadhar Card OCR extraction – 84% auto-verified', 'Passport manual verification queue – 3 pending', 'PAN Card cross-reference check enabled', 'Driving License barcode scan – automated', 'Biometric facial match enabled'],
    accentColor: '#4f46e5',
  },
  id_verification_records: {
    title: 'ID Verification Records', icon: '🗃️', category: 'verification_center',
    stats: [{ label: 'Total Records', value: '28.4K' }, { label: 'This Month', value: 4820 }, { label: 'Retention Policy', value: '6 months' }],
    items: ['All ID scans stored with AES-256 encryption', 'GDPR + India PDPB compliant data handling', 'Automatic record purge after 6-month retention window', 'Export ID records for audit purposes (Super Admin only)', 'Visitor consent captured digitally at check-in'],
    accentColor: '#7c3aed',
  },

  // ─── Settings ───
  company_settings: {
    title: 'Company Settings', icon: '🏢', category: 'settings',
    stats: [{ label: 'Org Name', value: 'Forge India Connect' }, { label: 'Plan', value: 'Enterprise' }, { label: 'Active Since', value: '2024' }],
    items: ['Organisation: Forge India Connect Pvt Ltd', 'CIN: U72200TN2024PTC123456', 'GST: 33AABCU1234F1ZV', 'Registered Office: Chennai, Tamil Nadu – 600001', 'Primary Contact: admin@forgeindia.com | +91 44 1234 5678'],
    accentColor: '#4f46e5',
  },
  branding_logo: {
    title: 'Branding & Logo', icon: '🎨', category: 'settings',
    stats: [{ label: 'Logo Uploaded', value: 'Yes' }, { label: 'Custom Colors', value: 'Active' }, { label: 'White-label', value: 'On' }],
    items: ['Primary Brand Color: #4f46e5 (Indigo)', 'Logo: /public/forge-logo.svg', 'Visitor Pass Template: Premium Corporate', 'Email Header Logo: Custom upload enabled', 'Portal Domain: visitors.forgeindia.com'],
    accentColor: '#7c3aed',
  },
  theme_settings: {
    title: 'Theme Settings', icon: '🌙', category: 'settings',
    stats: [{ label: 'Current Theme', value: 'Auto' }, { label: 'Custom CSS', value: 'Disabled' }, { label: 'Font', value: 'Inter' }],
    items: ['Default Theme: System preference (Auto light/dark)', 'Dashboard Font: Inter', 'Visitor Pass Font: Outfit', 'Animation Level: Full (Glassmorphism + Micro-animations)', 'Color Scheme: Indigo + Violet gradient'],
    accentColor: '#06b6d4',
  },
  security_settings: {
    title: 'Security Settings', icon: '🔐', category: 'settings',
    stats: [{ label: 'MFA Enabled', value: 'Yes' }, { label: 'Session Timeout', value: '30 min' }, { label: 'IP Whitelist', value: '3 IPs' }],
    items: ['Two-Factor Authentication: TOTP required', 'Password Policy: Min 12 chars', 'Session Auto-logout: After 30 minutes of inactivity', 'IP Whitelist: 3 office IPs whitelisted for admin access', 'Failed Login Lockout: After 5 attempts'],
    accentColor: '#ef4444',
  },
  email_templates: {
    title: 'Email Templates', icon: '✉️', category: 'settings',
    stats: [{ label: 'Templates', value: 12 }, { label: 'Custom', value: 5 }, { label: 'Last Edited', value: 'Recent' }],
    items: ['visitor_welcome.html – Customized ✓', 'host_alert.html – Default template', 'approval_request.html – Customized ✓', 'daily_digest.html – Customized ✓', 'pass_expiry.html – Default template'],
    accentColor: '#f59e0b',
  },
  notification_templates: {
    title: 'Notification Templates', icon: '📨', category: 'settings',
    stats: [{ label: 'SMS Templates', value: 8 }, { label: 'Push Templates', value: 6 }, { label: 'Variables', value: 18 }],
    items: ['visitor_arrival_sms – "Your visitor {name} has arrived."', 'pass_generated_sms – "Pass {passId} ready. Show QR at gate."', 'meeting_reminder_push – "{host} meeting in 15 min."', 'security_alert_push – "⚠ HIGH RISK visitor at {branch}"', 'checkout_sms – "Thank you for visiting Forge India, {name}."'],
    accentColor: '#10b981',
  },
};

export default function GenericModule({ tabId, setActiveTab, compact = false }) {
  const { isDark } = useTheme();
  const config = moduleContent[tabId];

  const handleExportCSV = () => {
    if (!config) return;
    const csvContent = "data:text/csv;charset=utf-8," 
      + `Report Title,${config.title}\n`
      + `Metric,Value\n`
      + config.stats.map(s => `"${s.label}","${s.value}"`).join("\n") + "\n\n"
      + "Log Details\n"
      + config.items.map(item => `"${item.replace(/"/g, '""')}"`).join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${config.title.toLowerCase().replace(/\s+/g, '_')}_report.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!config) {
    return (
      <div style={{ textAlign: 'center', padding: '6rem 2rem', color: isDark ? '#64748b' : '#94a3b8' }}>
        <div style={{ fontSize: 56, marginBottom: 16 }}>🚧</div>
        <h3 style={{ color: isDark ? '#f8fafc' : '#0f172a' }}>Module View</h3>
        <p>Tab ID "{tabId}" overview page.</p>
        {setActiveTab && (
          <button
            onClick={() => setActiveTab('reports_analytics')}
            style={{ marginTop: 16, padding: '8px 16px', borderRadius: 8, background: '#4f46e5', color: 'white', border: 0, fontWeight: 700, cursor: 'pointer' }}
          >
            ← Back to Overview
          </button>
        )}
      </div>
    );
  }

  const parentTab = config.category || 'reports_analytics';

  const glass = { background: isDark ? 'rgba(30,41,59,0.7)' : '#ffffff', backdropFilter: 'blur(20px)', border: isDark ? '1px solid rgba(255,255,255,0.07)' : '1px solid rgba(0,0,0,0.05)', borderRadius: 20, boxShadow: isDark ? '0 4px 24px rgba(0,0,0,0.25)' : '0 4px 24px rgba(148,163,184,0.1)' };

  return (
    <motion.div variants={staggerContainer} initial="hidden" animate="visible" style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Back button header */}
      {setActiveTab && (
        <motion.div variants={fadeUpBounce}>
          <button
            onClick={() => setActiveTab(parentTab)}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '8px 16px',
              borderRadius: 10,
              background: isDark ? 'rgba(255,255,255,0.06)' : '#f1f5f9',
              border: isDark ? '1px solid rgba(255,255,255,0.1)' : '1px solid #cbd5e1',
              color: isDark ? '#f8fafc' : '#0f172a',
              fontSize: 13,
              fontWeight: 700,
              cursor: 'pointer'
            }}
          >
            <ArrowLeft size={16} /> Back to Overview
          </button>
        </motion.div>
      )}

      {/* Header */}
      <motion.div variants={fadeUpBounce} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <div style={{ fontSize: 36 }}>{config.icon}</div>
          <div>
            <h2 style={{ margin: 0, fontSize: 24, fontWeight: 800, color: isDark ? '#f8fafc' : '#0f172a' }}>{config.title}</h2>
            <div style={{ display: 'flex', gap: 12, marginTop: 10, flexWrap: 'wrap' }}>
              {config.stats.map(s => (
                <div key={s.label} style={{ ...glass, padding: '10px 18px', borderRadius: 12, textAlign: 'center', minWidth: 100 }}>
                  <p style={{ margin: 0, fontSize: 18, fontWeight: 800, color: config.accentColor }}>{s.value}</p>
                  <p style={{ margin: '2px 0 0', fontSize: 11, color: isDark ? '#94a3b8' : '#64748b', fontWeight: 600 }}>{s.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Export & Print actions */}
        <div style={{ display: 'flex', gap: 10 }}>
          <button
            onClick={handleExportCSV}
            style={{
              padding: '10px 18px',
              borderRadius: 10,
              background: '#4f46e5',
              color: 'white',
              border: 0,
              fontWeight: 700,
              fontSize: 13,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              cursor: 'pointer',
              boxShadow: '0 4px 12px rgba(79, 70, 229, 0.3)'
            }}
          >
            <Download size={16} /> Export CSV
          </button>
          <button
            onClick={() => window.print()}
            style={{
              padding: '10px 16px',
              borderRadius: 10,
              background: isDark ? 'rgba(255,255,255,0.06)' : '#e2e8f0',
              color: isDark ? '#f8fafc' : '#334155',
              border: 0,
              fontWeight: 700,
              fontSize: 13,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              cursor: 'pointer'
            }}
          >
            <Printer size={16} /> Print
          </button>
        </div>
      </motion.div>

      {/* Content List */}
      <motion.div variants={fadeUpBounce} style={{ ...glass, padding: 28 }}>
        <h3 style={{ margin: '0 0 20px', fontSize: 15, fontWeight: 700, color: isDark ? '#f8fafc' : '#0f172a', borderBottom: isDark ? '1px solid rgba(255,255,255,0.06)' : '1px solid rgba(0,0,0,0.06)', paddingBottom: 14 }}>
          Live Log & Breakdown Details
        </h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {config.items.map((item, i) => (
            <motion.div key={i}
              initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.07 }}
              style={{ padding: '14px 0', borderBottom: i < config.items.length - 1 ? (isDark ? '1px solid rgba(255,255,255,0.04)' : '1px solid rgba(0,0,0,0.04)') : 'none', display: 'flex', alignItems: 'flex-start', gap: 14 }}>
              <div style={{ width: 6, height: 6, borderRadius: '50%', background: config.accentColor, marginTop: 7, flexShrink: 0 }} />
              <p style={{ margin: 0, fontSize: 14, color: isDark ? '#cbd5e1' : '#475569', lineHeight: 1.5 }}>{item}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}
