"use client";
/**
 * GenericModule.jsx
 * A premium, content-rich placeholder for modules that share common UI patterns.
 * Used for: Administration, Reports, Membership, Notifications, Verification, Settings sub-tabs.
 */
import React from 'react';
import { motion } from 'framer-motion';
import { staggerContainer, fadeUpBounce } from '../../utils/animations';
import { useTheme } from '../../context/ThemeContext';

const moduleContent = {
  // ─── Administration ───
  sub_admins: {
    title: 'Sub Admins', icon: '🛡️',
    stats: [{ label: 'Total Sub-Admins', value: 8 }, { label: 'Active', value: 7 }, { label: 'Branches Covered', value: 6 }],
    items: ['Arjun Pillai – Chennai HQ – Full Access', 'Ritu Joshi – Mumbai Branch – Visitor Only', 'Deepa Nair – Hyderabad – Visitor + Reports', 'Vikram Singh – Delhi NCR – Full Access', 'Anita Desai – Pune – Visitor Only'],
    accentColor: '#4f46e5',
  },
  roles_permissions: {
    title: 'Roles & Permissions', icon: '🔐',
    stats: [{ label: 'Roles Defined', value: 6 }, { label: 'Custom Permissions', value: 24 }, { label: 'Policy Rules', value: 12 }],
    items: ['Super Admin – Full system access', 'Org Admin – Branch-level full access', 'HR – Employee + visitor management', 'Security – Check-in/out + verification', 'Receptionist – Visitor passes + bookings', 'Employee – View-only personal data'],
    accentColor: '#7c3aed',
  },
  access_control: {
    title: 'Access Control', icon: '🔒',
    stats: [{ label: 'Secured Areas', value: 12 }, { label: 'Zones', value: 5 }, { label: 'IP Restrictions', value: 3 }],
    items: ['Zone A: Executive Floor – RFID + Biometric', 'Zone B: Server Room – Biometric Only', 'Zone C: HR Office – Badge Access', 'Zone D: Meeting Rooms – Visitor Pass', 'Zone E: Public Lobby – Open Access'],
    accentColor: '#dc2626',
  },
  login_activity: {
    title: 'Login Activity', icon: '📡',
    stats: [{ label: 'Sessions Today', value: 42 }, { label: 'Failed Logins', value: 3 }, { label: 'Active Sessions', value: 8 }],
    items: ['admin@forgeindia.com – Chrome – Chennai – 09:12 AM ✓', 'arjun.pillai@forgeindia.com – Edge – Mumbai – 09:45 AM ✓', 'ritu.joshi@forgeindia.com – Firefox – Hyderabad – 10:01 AM ✓', 'unknown@example.com – Safari – Unknown IP – 10:22 AM ✗ FAILED', 'deepa.nair@forgeindia.com – Chrome – Pune – 11:05 AM ✓'],
    accentColor: '#0284c7',
  },
  audit_logs: {
    title: 'Audit Logs', icon: '📋',
    stats: [{ label: 'Logs Today', value: 234 }, { label: 'Critical Events', value: 2 }, { label: 'Data Changes', value: 18 }],
    items: ['[10:22] WARN  – Failed login attempt – unknown@example.com', '[10:18] INFO  – Visitor VB-005 pass generated by admin', '[10:05] INFO  – Employee EMP-048 profile updated', '[09:55] CRIT  – Access denied: Zone B attempted by VB-003', '[09:40] INFO  – Branch Chennai: visitor capacity updated to 150'],
    accentColor: '#b45309',
  },

  // ─── Reports & Analytics ───
  daily_reports: {
    title: 'Daily Reports', icon: '📊',
    stats: [{ label: 'Reports Generated', value: 6 }, { label: 'Total Visitors', value: 255 }, { label: 'Avg Check-in Time', value: '4.2 min' }],
    items: ['All Branches Daily Summary – June 20, 2026', 'Visitor Type Breakdown – Guest: 112, Vendor: 87, VIP: 34, Interviewee: 22', 'Peak Hour Report – 10:00–11:30 AM (68 visitors)', 'Security Incidents – 1 flagged (High Risk visitor)', 'Approval Rate – 94.2% approved, 5.8% rejected'],
    accentColor: '#4f46e5',
  },
  weekly_reports: {
    title: 'Weekly Reports', icon: '📅',
    stats: [{ label: 'Week Total', value: 1240 }, { label: 'Growth vs Last Week', value: '+8.4%' }, { label: 'Branches Reported', value: 6 }],
    items: ['Jun 14–20 Summary: 1,240 visitors across 6 branches', 'Top Branch: Chennai HQ – 412 visitors', 'Highest Growth: Mumbai +14.2% week-on-week', 'Most Common Purpose: Business Meeting (38%)', 'Average Dwell Time: 2.3 Hours'],
    accentColor: '#7c3aed',
  },
  monthly_reports: {
    title: 'Monthly Reports', icon: '🗓️',
    stats: [{ label: 'Month Total', value: 4820 }, { label: 'New Branches', value: 1 }, { label: 'Compliance Rate', value: '96.8%' }],
    items: ['June 2026 Report – 4,820 total visitors, ↑12% vs May', 'Branch Expansion: Pune Tech Park opened June 5', 'Compliance Score: 96.8% average across all branches', 'Top Visitor Category: Vendor (42% of all visits)', 'Zero data breach incidents – 100% ID verification rate'],
    accentColor: '#0891b2',
  },
  visitor_trends: {
    title: 'Visitor Trends', icon: '📈',
    stats: [{ label: 'YTD Visitors', value: '28.4K' }, { label: 'MoM Growth', value: '+12%' }, { label: 'Peak Month', value: 'March' }],
    items: ['Q1 2026: 9,240 visitors – Baseline period', 'Q2 2026 (projected): 11,400 visitors – +23.4%', 'Fastest growing category: VIP visits (+34% YoY)', 'Seasonal peak: March–April (monsoon avoidance travel)', 'Predicted all-time high: August 2026 (2,400+ expected)'],
    accentColor: '#10b981',
  },
  peak_visit_hours: {
    title: 'Peak Visit Hours', icon: '⏰',
    stats: [{ label: 'Busiest Hour', value: '10 AM' }, { label: 'Avg Daily Peak', value: '9–11 AM' }, { label: 'Slowest Period', value: '2–3 PM' }],
    items: ['Morning Rush (9–11 AM): 42% of daily visits', 'Post-Lunch Lull (1–3 PM): 12% of daily visits', 'Evening Surge (4–6 PM): 28% of daily visits', 'Friday is busiest day (18% above weekly avg)', 'Monday mornings show highest no-show rate (11%)'],
    accentColor: '#f59e0b',
  },
  export_reports: {
    title: 'Export Reports', icon: '⬇️',
    stats: [{ label: 'Formats Available', value: 4 }, { label: 'Last Export', value: 'Today' }, { label: 'Scheduled Exports', value: 3 }],
    items: ['📄 PDF – Full formatted report with charts', '📊 Excel (.xlsx) – Raw data for analysis', '📋 CSV – Universal data format', '📧 Email Delivery – Schedule weekly/monthly auto-sends', '🔗 API Export – Integrate with your BI tool (Power BI, Tableau)'],
    accentColor: '#06b6d4',
  },

  // ─── Employee Sub-tabs ───
  department_management: {
    title: 'Department Management', icon: '🏛️',
    stats: [{ label: 'Departments', value: 12 }, { label: 'Employees', value: 821 }, { label: 'Open Roles', value: 7 }],
    items: ['Engineering – 245 employees – Dept Head: Nikhil Sharma', 'Sales & Marketing – 134 employees – Dept Head: Raj Kumar', 'HR & Administration – 89 employees – Dept Head: Sunita Rao', 'Finance & Accounts – 76 employees – Dept Head: Anika Bose', 'Operations – 112 employees – Dept Head: Deepa Nair'],
    accentColor: '#4f46e5',
  },
  host_directory: {
    title: 'Host Directory', icon: '👤',
    stats: [{ label: 'Total Hosts', value: 312 }, { label: 'Available Now', value: 187 }, { label: 'In Meeting', value: 64 }],
    items: ['Priya Nair – Engineering – priya.nair@forgeindia.com – ✓ Available', 'Raj Kumar – Sales – raj.kumar@forgeindia.com – ✓ Available', 'Anika Bose – Finance – anika.bose@forgeindia.com – 🔴 In Meeting', 'Dev Singh – IT – dev.singh@forgeindia.com – ✓ Available', 'Geeta Singh – Legal – geeta.singh@forgeindia.com – 🟡 Away'],
    accentColor: '#7c3aed',
  },

  // ─── Membership ───
  silver_plan: {
    title: 'Silver Plan', icon: '🥈',
    stats: [{ label: 'Active Subscribers', value: 48 }, { label: 'Monthly Revenue', value: '₹2.4L' }, { label: 'Renewal Rate', value: '88%' }],
    items: ['₹4,999/month – Up to 1 branch', 'Up to 500 visitors/month', 'Basic visitor pass generation', 'Email notifications included', 'Standard support (24–48 hr response)'],
    accentColor: '#94a3b8',
  },
  gold_plan: {
    title: 'Gold Plan', icon: '🥇',
    stats: [{ label: 'Active Subscribers', value: 86 }, { label: 'Monthly Revenue', value: '₹8.6L' }, { label: 'Renewal Rate', value: '92%' }],
    items: ['₹9,999/month – Up to 3 branches', 'Up to 2,000 visitors/month', 'Advanced QR pass generation', 'SMS + Email notifications', 'Priority support (4–8 hr response)'],
    accentColor: '#f59e0b',
  },
  diamond_plan: {
    title: 'Diamond Plan', icon: '💎',
    stats: [{ label: 'Active Subscribers', value: 34 }, { label: 'Monthly Revenue', value: '₹10.2L' }, { label: 'Renewal Rate', value: '97%' }],
    items: ['₹24,999/month – Up to 10 branches', 'Unlimited visitors/month', 'Full biometric integration', 'SMS + Email + Push notifications', 'Dedicated account manager'],
    accentColor: '#06b6d4',
  },
  platinum_plan: {
    title: 'Platinum Plan', icon: '👑',
    stats: [{ label: 'Active Subscribers', value: 12 }, { label: 'Monthly Revenue', value: '₹12L' }, { label: 'Renewal Rate', value: '100%' }],
    items: ['₹49,999/month – Unlimited branches', 'Unlimited visitors + custom branding', 'White-label solution available', '99.9% SLA guarantee', 'On-premise deployment option + 24/7 dedicated support'],
    accentColor: '#8b5cf6',
  },
  subscription_history: {
    title: 'Subscription History', icon: '🧾',
    stats: [{ label: 'Total Transactions', value: 384 }, { label: 'This Month', value: 28 }, { label: 'Refunds', value: 2 }],
    items: ['#TXN-1042 – Forge India Connect – Platinum – ₹49,999 – Paid ✓', '#TXN-1041 – TechCorp Ltd – Diamond – ₹24,999 – Paid ✓', '#TXN-1040 – StartupX – Gold – ₹9,999 – Paid ✓', '#TXN-1039 – FinSolve Inc – Silver – ₹4,999 – Paid ✓', '#TXN-1038 – CloudBase – Diamond – ₹24,999 – Refunded ✗'],
    accentColor: '#4f46e5',
  },
  renewal_management: {
    title: 'Renewal Management', icon: '🔄',
    stats: [{ label: 'Due This Month', value: 14 }, { label: 'Overdue', value: 2 }, { label: 'Auto-Renew On', value: 9 }],
    items: ['🔴 OVERDUE: CloudBase – Diamond – Expired Jun 15', '🟡 DUE IN 3 DAYS: Infosys Solutions – Gold – Jun 23', '🟡 DUE IN 7 DAYS: HRConnect – Silver – Jun 27', '🟢 AUTO-RENEW: Forge India Connect – Platinum – Jul 1', '🟢 AUTO-RENEW: StartupX – Gold – Jul 5'],
    accentColor: '#f59e0b',
  },

  // ─── Notifications ───
  sms_notifications: {
    title: 'SMS Notifications', icon: '📱',
    stats: [{ label: 'Sent Today', value: 342 }, { label: 'Delivery Rate', value: '98.7%' }, { label: 'Templates', value: 8 }],
    items: ['Visitor Arrival Alert – "Your visitor [Name] has arrived at Reception"', 'Pass Generated – "[Name], your pass [ID] is ready. Show QR at gate."', 'Meeting Reminder – "Your meeting with [Host] starts in 15 minutes"', 'Check-out Confirmation – "Visit complete. Thank you for visiting Forge India."', 'Security Alert – "⚠ Flagged visitor attempting entry at [Branch]"'],
    accentColor: '#10b981',
  },
  email_notifications: {
    title: 'Email Notifications', icon: '📧',
    stats: [{ label: 'Sent Today', value: 218 }, { label: 'Open Rate', value: '74.3%' }, { label: 'Templates', value: 12 }],
    items: ['Welcome Email – Sent to visitor upon pass generation', 'Host Alert – Notifies host when visitor checks in', 'Approval Request – Sent to host for meeting approval', 'Daily Digest – Admin summary of all visits (7 AM daily)', 'Expiry Warning – Notifies visitor 30 min before pass expires'],
    accentColor: '#4f46e5',
  },
  push_notifications: {
    title: 'Push Notifications', icon: '🔔',
    stats: [{ label: 'Active Devices', value: 84 }, { label: 'Sent Today', value: 156 }, { label: 'Click Rate', value: '62.1%' }],
    items: ['Real-time visitor arrival alerts to mobile app', 'Security incident push to all Security role users', 'Approval requests to host devices instantly', 'Check-in/out updates to reception staff', 'Branch manager daily KPI summary at 6 PM'],
    accentColor: '#7c3aed',
  },
  alert_center: {
    title: 'Alert Center', icon: '🚨',
    stats: [{ label: 'Active Alerts', value: 4 }, { label: 'Critical', value: 1 }, { label: 'Resolved Today', value: 12 }],
    items: ['🔴 CRITICAL: High-risk visitor AQ-004 awaiting clearance – Zone B attempted', '🟡 WARN: Delhi NCR branch under maintenance – visitor capacity 0', '🟡 WARN: Renewal overdue for CloudBase account (3 days)', '🔵 INFO: Scheduled server maintenance Jun 22, 2:00 AM – 4:00 AM', '✅ RESOLVED: Login anomaly flagged at 10:22 AM – Blocked & logged'],
    accentColor: '#ef4444',
  },

  // ─── Verification Center ───
  qr_pass_generator: {
    title: 'QR Pass Generator', icon: '🔲',
    stats: [{ label: 'Generated Today', value: 87 }, { label: 'Active Passes', value: 54 }, { label: 'Scanned', value: 73 }],
    items: ['Auto-generate QR passes on visitor approval', 'Time-limited QR codes (expire at check-out)', 'Supports visitor self-service QR via SMS/Email', 'Multi-pass batch generation for large groups', 'Integration with physical access control systems'],
    accentColor: '#0284c7',
  },
  qr_scan_logs: {
    title: 'QR Scan Logs', icon: '📷',
    stats: [{ label: 'Scans Today', value: 214 }, { label: 'Successful', value: 208 }, { label: 'Failed/Invalid', value: 6 }],
    items: ['[10:45 AM] PASS V-2041 – Kartik Mehta – Gate A – ✓ Valid', '[10:42 AM] PASS V-2040 – Preethi Suresh – Gate B – ✓ Valid', '[10:38 AM] PASS V-1998 – Ravi Verma – Gate A – ✗ Expired', '[10:30 AM] PASS V-2039 – Akash Singh – Gate C – ✓ Valid', '[10:22 AM] UNKNOWN QR – Unregistered code – Gate B – ✗ BLOCKED'],
    accentColor: '#10b981',
  },
  visitor_verification: {
    title: 'Visitor Verification', icon: '✅',
    stats: [{ label: 'Verified Today', value: 87 }, { label: 'Pending ID Check', value: 6 }, { label: 'Failed Verification', value: 2 }],
    items: ['Aadhar Card OCR extraction – 84% auto-verified', 'Passport manual verification queue – 3 pending', 'PAN Card cross-reference check enabled', 'Driving License barcode scan – automated', 'Biometric facial match – Available for Platinum plan'],
    accentColor: '#4f46e5',
  },
  id_verification_records: {
    title: 'ID Verification Records', icon: '🗃️',
    stats: [{ label: 'Total Records', value: '28.4K' }, { label: 'This Month', value: 4820 }, { label: 'Retention Policy', value: '6 months' }],
    items: ['All ID scans stored with AES-256 encryption', 'GDPR + India PDPB compliant data handling', 'Automatic record purge after 6-month retention window', 'Export ID records for audit purposes (Super Admin only)', 'Visitor consent captured digitally at check-in'],
    accentColor: '#7c3aed',
  },

  // ─── Settings ───
  company_settings: {
    title: 'Company Settings', icon: '🏢',
    stats: [{ label: 'Org Name', value: 'Forge India Connect' }, { label: 'Plan', value: 'Platinum' }, { label: 'Active Since', value: '2024' }],
    items: ['Organisation: Forge India Connect Pvt Ltd', 'CIN: U72200TN2024PTC123456', 'GST: 33AABCU1234F1ZV', 'Registered Office: Chennai, Tamil Nadu – 600001', 'Primary Contact: admin@forgeindia.com | +91 44 1234 5678'],
    accentColor: '#4f46e5',
  },
  branding_logo: {
    title: 'Branding & Logo', icon: '🎨',
    stats: [{ label: 'Logo Uploaded', value: 'Yes' }, { label: 'Custom Colors', value: 'Active' }, { label: 'White-label', value: 'On' }],
    items: ['Primary Brand Color: #4f46e5 (Indigo)', 'Logo: /public/forge-logo.svg – Last updated June 1, 2026', 'Visitor Pass Template: Premium Corporate (dark + light)', 'Email Header Logo: Custom upload enabled', 'Portal Domain: visitors.forgeindia.com (Custom domain active)'],
    accentColor: '#7c3aed',
  },
  theme_settings: {
    title: 'Theme Settings', icon: '🌙',
    stats: [{ label: 'Current Theme', value: 'Auto' }, { label: 'Custom CSS', value: 'Disabled' }, { label: 'Font', value: 'Inter' }],
    items: ['Default Theme: System preference (Auto light/dark)', 'Dashboard Font: Inter – Google Fonts', 'Visitor Pass Font: Outfit – Clean & modern', 'Animation Level: Full (Glassmorphism + Micro-animations)', 'Color Scheme: Indigo + Violet gradient (customizable per branch)'],
    accentColor: '#06b6d4',
  },
  security_settings: {
    title: 'Security Settings', icon: '🔐',
    stats: [{ label: 'MFA Enabled', value: 'Yes' }, { label: 'Session Timeout', value: '30 min' }, { label: 'IP Whitelist', value: '3 IPs' }],
    items: ['Two-Factor Authentication: TOTP (Google Authenticator) required', 'Password Policy: Min 12 chars, uppercase + symbols', 'Session Auto-logout: After 30 minutes of inactivity', 'IP Whitelist: 3 office IPs whitelisted for admin access', 'Failed Login Lockout: After 5 attempts, 15-minute cooldown'],
    accentColor: '#ef4444',
  },
  email_templates: {
    title: 'Email Templates', icon: '✉️',
    stats: [{ label: 'Templates', value: 12 }, { label: 'Custom', value: 5 }, { label: 'Last Edited', value: 'Jun 18' }],
    items: ['visitor_welcome.html – Customized ✓ (Jun 18)', 'host_alert.html – Default template', 'approval_request.html – Customized ✓ (Jun 10)', 'daily_digest.html – Customized ✓ (Jun 15)', 'pass_expiry.html – Default template'],
    accentColor: '#f59e0b',
  },
  notification_templates: {
    title: 'Notification Templates', icon: '📨',
    stats: [{ label: 'SMS Templates', value: 8 }, { label: 'Push Templates', value: 6 }, { label: 'Variables', value: 18 }],
    items: ['visitor_arrival_sms – "Your visitor {name} has arrived."', 'pass_generated_sms – "Pass {passId} ready. Show QR at gate."', 'meeting_reminder_push – "{host} meeting in 15 min."', 'security_alert_push – "⚠ HIGH RISK visitor at {branch}"', 'checkout_sms – "Thank you for visiting Forge India, {name}."'],
    accentColor: '#10b981',
  },
};

export default function GenericModule({ tabId, compact = false }) {
  const { isDark } = useTheme();
  const config = moduleContent[tabId];

  if (!config) {
    return (
      <div style={{ textAlign: 'center', padding: '6rem 2rem', color: isDark ? '#64748b' : '#94a3b8' }}>
        <div style={{ fontSize: 56, marginBottom: 16 }}>🚧</div>
        <h3 style={{ color: isDark ? '#f8fafc' : '#0f172a' }}>Unknown Module</h3>
        <p>Tab ID "{tabId}" has no content configured.</p>
      </div>
    );
  }

  const glass = { background: isDark ? 'rgba(30,41,59,0.7)' : '#ffffff', backdropFilter: 'blur(20px)', border: isDark ? '1px solid rgba(255,255,255,0.07)' : '1px solid rgba(0,0,0,0.05)', borderRadius: 20, boxShadow: isDark ? '0 4px 24px rgba(0,0,0,0.25)' : '0 4px 24px rgba(148,163,184,0.1)' };

  if (compact) {
    return (
      <motion.div variants={staggerContainer} initial="hidden" animate="visible" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <motion.div variants={fadeUpBounce} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ fontSize: 24 }}>{config.icon}</div>
          <h2 style={{ margin: 0, fontSize: 18, fontWeight: 800, color: isDark ? '#f8fafc' : '#0f172a' }}>{config.title}</h2>
        </motion.div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10 }}>
          {config.stats.map(s => (
            <div key={s.label} style={{ ...glass, padding: '12px 10px', borderRadius: 12, textAlign: 'center' }}>
              <p style={{ margin: 0, fontSize: 16, fontWeight: 800, color: config.accentColor }}>{s.value}</p>
              <p style={{ margin: '2px 0 0', fontSize: 10, color: isDark ? '#94a3b8' : '#64748b', fontWeight: 600 }}>{s.label}</p>
            </div>
          ))}
        </div>

        <motion.div variants={fadeUpBounce} style={{ marginTop: 8 }}>
          <h3 style={{ margin: '0 0 12px', fontSize: 13, fontWeight: 700, color: isDark ? '#f8fafc' : '#0f172a', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            Overview
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {config.items.slice(0, 3).map((item, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}>
                <div style={{ width: 6, height: 6, borderRadius: '50%', background: config.accentColor, marginTop: 6, flexShrink: 0 }} />
                <p style={{ margin: 0, fontSize: 12, color: isDark ? '#cbd5e1' : '#475569', lineHeight: 1.4 }}>{item}</p>
              </div>
            ))}
          </div>
        </motion.div>
      </motion.div>
    );
  }

  return (
    <motion.div variants={staggerContainer} initial="hidden" animate="visible" style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Header */}
      <motion.div variants={fadeUpBounce} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
        <div style={{ fontSize: 36 }}>{config.icon}</div>
        <div>
          <h2 style={{ margin: 0, fontSize: 24, fontWeight: 800, color: isDark ? '#f8fafc' : '#0f172a' }}>{config.title}</h2>
          <div style={{ display: 'flex', gap: 12, marginTop: 10, flexWrap: 'wrap' }}>
            {config.stats.map(s => (
              <div key={s.label} style={{ ...glass, padding: '10px 18px', borderRadius: 12, textAlign: 'center', minWidth: 100 }}>
                <p style={{ margin: 0, fontSize: 18, fontWeight: 800, color: config.accentColor }}>{s.value}</p>
                <p style={{ margin: '2px 0 0', fontSize: 11, color: isDark ? '#94a3b8' : '#64748b', fontWeight: 600 }}>{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      {/* Content List */}
      <motion.div variants={fadeUpBounce} style={{ ...glass, padding: 28 }}>
        <h3 style={{ margin: '0 0 20px', fontSize: 15, fontWeight: 700, color: isDark ? '#f8fafc' : '#0f172a', borderBottom: isDark ? '1px solid rgba(255,255,255,0.06)' : '1px solid rgba(0,0,0,0.06)', paddingBottom: 14 }}>
          Overview
        </h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {config.items.map((item, i) => (
            <motion.div key={i}
              initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.07 }}
              style={{ padding: '14px 0', borderBottom: i < config.items.length - 1 ? (isDark ? '1px solid rgba(255,255,255,0.04)' : '1px solid rgba(0,0,0,0.04)') : 'none', display: 'flex', alignItems: 'flex-start', gap: 14 }}>
              <div style={{ width: 6, height: 6, borderRadius: '50%', background: config.accentColor, marginTop: 7, flexShrink: 0 }} />
              <p style={{ margin: 0, fontSize: 14, color: isDark ? '#cbd5e1' : '#475569', lineHeight: 1.5 }}>{item}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}
